### ISSUE TITLE
fix all the searches

### ISSUE THREAD

**Issue by nathandunn** [monarch-initiative/monarch-ui#1]
I may break this into multiple issues, but this is everything I have for now.

adapted from:  https://github.com/monarch-initiative/monarch-ui/issues/1#issuecomment-424805051

- ~~Filter button itself shouldn't be multiselect~~ moved to #2
- [x] home page should use the same filter as the one at the top
- [x]  Have the filters menu at the left of navbar (equivalent to what is on the node pages already). There is a single vue widget driving both of these so the trick would be to adapt the homepage autocomplete to look more like navbar autocomplete. Doing so will remove the
- [x]  That "filters" button (in both places, home and navbar) should instead say "All"
- [x]  add 'e.g.:' before the search examples  **(ND . . I didn't see this)**
- [x]  remove 'marfan syndrome disease' as one of the examples. 'syndrome disease' is an odd pairing.

--- 

- ~~Wire up the "search in all results" to give you what you get here https://alpha.monarchinitiative.org/search/marfan ~~ moved to #5 

- ~~autopopulate the first item of autocomplete results as "search < foo > in all results"; it is appropriate that this item be preselected so that if the user presses 'enter' they get to the search results page with facets.~~ **(ND: I think this is a bad idea UI-wise and is more complex to implement than what I put in there (by default if nothing is selected, do the full search).  This follows the UI convections of both AMZN and GOOGLE )**

=== 

- [x]  add a search button to the right of the search bar (home page version only) (this is configurable with the show-search-button)

**Comment by DoctorBud** [comment]
The 'text search' feature is probably most easily implemented by porting the VueJS code in monarch-app over into a VueJS SFC. The components are:
- templates/search_results.mustache (for the HTML template)
- js/search_results.js (for the behavior of the component)
- The webapp.js function `searchApiHandler` (server-side) needs to be replaced with a client-side implementation that uses BL.
- There's a BL function already used for autocomplete in BioLink.js called `getSearchTermSuggestions()`. An analogous function could be created that does text search (and it has to deal with paging).

**Comment by jmcmurry** [comment]
Home page search should look like this:

![image](https://user-images.githubusercontent.com/3658863/46097810-aea33280-c177-11e8-8d05-436b89e1015f.png)

The specific items in order of importance are:
- [ ] autopopulate the first item of autocomplete results as "search < foo > in all results"; it is appropriate that this item be preselected so that if the user presses 'enter' they get to the search results page with facets.
- [ ] Wire up the "search in all results" to give you what you get here https://alpha.monarchinitiative.org/search/marfan
- [ ] Have the filters menu at the left of navbar (equivalent to what is on the node pages already). There is a single vue widget driving both of these so the trick would be to adapt the homepage autocomplete to look more like navbar autocomplete.
- [ ] That "filters" button (in both places, home and navbar) should instead say "All"
- [ ] On reflection, I feel that the filter button itself shouldn't be multiselect; it should be a dropdown as it is in HPO; making it multiselect overloads/overcomplicates autocomplete. Raises issues like when to display or close the dropdown, what do display in the button if it is hidden etc. etc. If someone is trying to get the result of multiple categories they can select "in all results" and facet results from there. Since we don't have 25 categories, I don't feel that this is too much to ask of users. It is also easier to build and life is short.
- [ ] add 'e.g.:' before the search examples
- [ ] remove 'marfan syndrome disease' as one of the examples. 'syndrome disease' is an odd pairing.

Thanks!

**Comment by nathandunn** [comment]
@jmcmurry  I need to be able to edit the issues so I can update the check boxes. 

Also, its better to let me edit the todo-list based on your comments.

**Comment by jmcmurry** [comment]
@nathandunn np for you to edit both the list and the check boxes; you should have perms to do so now.

**Comment by jmcmurry** [comment]
Just an FYI, the longer term vision of autocomplete rendering is described [here](https://github.com/monarch-initiative/monarch-app/issues/1008) with rationale. 
The JAX HPO autocomplete comes close.
