### ISSUE TITLE
is likely pathogenic for condition

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-ui#142]
+/-

**Comment by pnrobinson** [comment]
@cmungall @mellybelly  PLEASE CAN WE NOT DO THIS -- CLINVAR JUST HAS TOO MUCH UNRELIABLE STUFF.

**Comment by kshefchek** [comment]
See https://github.com/monarch-initiative/monarch-ui/issues/139#issuecomment-514856101

This will be fixed in the next data load which will be on beta on Monday.  This did not make it to production, and this and couple other small things is why we are not releasing the latest data set.

https://monarchinitiative.org/disease/MONDO:0013612

**Comment by pnrobinson** [comment]
How will this be fixed? Are we completely removing the ClinVar associations?

**Comment by kshefchek** [comment]
https://beta.monarchinitiative.org/disease/MONDO:0013612 should be fixed now, @pnrobinson could you review and confirm?

**Comment by monicacecilia** [comment]
@kshefchek - what was the bug here, the wording 'likely pathogenic?'

if so, I don't see it on the pages any more. 

@pnrobinson is going away for a few weeks. If this is fixed, we should close this ticket. Thanks!
