### ISSUE TITLE
Issues with GO function tables on gene pages

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#167]
Referring to the contents of this page: http://beta.monarchinitiative.org/gene/HGNC:17158#function (leftover from #95) 

__1. On the subject of counting GO terms:__
- [ ] Toggle tick when this part has been fixed.
- [Questions](https://github.com/monarch-initiative/monarch-ui/issues/95#issuecomment-510581688) from @kshefchek: there are some oddities on this page:
  - We're saying there are 9 distinct GO terms (count in front of the word 'Function' on the left hand column) but I only see 7 (seven different GO terms listed in the results table that lists 10 associations)
  - Genes are linked to Uniprot IDs that don't resolve to blank pages. Do we need protein pages - or have these forward to the appropriate gene page?
  - Update: refer to [this BL ticket](https://github.com/biolink/biolink-api/issues/318)
- [Comment](https://github.com/monarch-initiative/monarch-ui/issues/95#issuecomment-510861157) from @pnrobinson: In answer to @kshefchek I think that currently we do not distinguish between the isoforms of a gene/protein, and so there is a 1:1 mapping from protein to gene. For right now, it would be fine to have uniprot's forward to the appropriate gene page. With new technologies such as long-read sequencing, it is likely that the community will try to do a better job in the future, and so we should try not to bake the idea of there being a 1:1 correspondence between protein and gene deeply into the logic of Dipper or of the ui.

__2. On the subject of counting associations:__
- [x] Toggle tick when this part has been fixed.
- There is a discrepancy on count of function associations in left column vs main results table. 
<img width="488" alt="Screen Shot 2019-08-07 at 3 54 09 PM" src="https://user-images.githubusercontent.com/1714621/62663265-a71def80-b92b-11e9-91c4-77504abdce9c.png">

**Comment by kshefchek** [comment]
Association counts fixed with https://github.com/biolink/biolink-api/pull/310

**Comment by deepakunni3** [comment]
> We're saying there are 9 distinct GO terms (count in front of the word 'Function' on the left hand column) but I only see 7 (seven different GO terms listed in the results table that lists 10 associations)

I think I know what is happening here.
When fetching counts we are getting the counts directly from Monarch Solr.
But when we are fetching the actual associations, we are fetching the results from GO Solr.
Ideally both Solr instances should be in-sync w.r.t. the content. But given the fact that both projects have different release schedules and timelines, this might not be a fair expectation.

The solution to this would be to make a separate call to GO Solr, when fetching counts. Of course this call would happen only when the entity type is a `gene`. @kshefchek Thoughts?

> Genes are linked to Uniprot IDs that don't resolve to blank pages. Do we need protein pages - or have these forward to the appropriate gene page?

I would say we should redirect to the appropriate gene page and make use of HTML anchor tags (or something similar) to highlight the section of the page where it says this protein is a product of this gene.

**Comment by kshefchek** [comment]
the function tab is showing a 500 error - https://beta.monarchinitiative.org/gene/HGNC:10848#function

Maybe it would be easier to use the monarch ingest of GO?  There seem to be nuances in using the GO driven biolink endpoints that we haven't worked out.  @deepakunni3 you know more about this than me and so I defer to you on this one!

**Comment by kshefchek** [comment]
so looks I broke this in my latest PR which I'm staging on dev, but this is fixed now.  But back to https://beta.monarchinitiative.org/gene/HGNC:10848#function, the issues I see are:
- duplicate GO terms
- genes leading to dead ends
- unknown for relation

**Comment by deepakunni3** [comment]
After debugging https://beta.monarchinitiative.org/gene/HGNC:10848#function here is what I noticed:

### Duplicate GO terms

There are 6 annotations being shown in the table for term `GO:0005515`. All of these associations have the same Solr document ID `556e6950726f744b4209513135343635095348480909474f3a3030303535313509504d49443a33303133393931320949504909556e6950726f744b423a5131333633352d31094609536f6e6963206865646765686f672070726f7465696e090970726f7465696e097461786f6e3a3936303609323031393036303209496e74416374090909`

What is different in each of them is the `evidence_with` field of the document. 

@kltm @cmungall Any idea what might be happening here? Is this expected?

### Genes leading to dead ends

The issue here is that the values in Gene column of the table is actually UniProtKB IDs.
Even though the current page is for HGNC:10848, we map the gene identifier to a protein identifier before querying GOlr. Thus the results are UniProtKB IDs.
And since Monarch does not have pages for proteins, it ends up being an empty page.

### Unknown for relation

It looks like the `relation` field is empty for all annotations fetched from GOlr.
As per the [AmiGO Schema](http://amigo.geneontology.org/amigo/schema_details) there is no `relation` field for an annotation.

**Comment by monicacecilia** [comment]
@kshefchek, @kltm, and I had a chat where we tried to dissect the way in which Monarch is currently organizing data into tables on gene pages. The working theory is that, at Monarch, we may be recreating data associations that GO has already loaded and displayed once, and then gotten rid of before displaying them in the association pages. There might be issues with how Monarch is using the GO-driven BioLink endpoints (we query the GO GOLR through BioLink).

Some notes from this conversation:
- GO works on trying to set up a system to mark the redundancies - marking annotations by ranking them, for example, discerning 'weaker' evidence codes, etc.
- On the Monarch pages, the functional annotation display does not give us enough information to learn why we see repetition (e.g. repeated GO terms in the ['Function' tab of this gene page](https://beta.monarchinitiative.org/gene/HGNC:10848#function)), and we (Monarch) need to figure out where the repetitiveness is coming from, and how to change it. One way to get rid of redundant info is to "punt it" to the GO; that is, consume those data directly from them, instead of processing them to run the loader again.  
- Monarch fishes through the information captured from the functional associations, looking for 'causal' relations with the list of phenotypes associated with each gene product.
- In AmiGO, a gene function page has: 
  - gene product info 
  - annotation info for gene product

### _Proposed_ ACTION: 
- For the purpose of populating only the 'Function' facet of the 'gene' pages in the Monarch website, would it be possible for Monarch to just make the two calls that a gene function page makes in AmiGO? 
  - We would be using the GO data directly, through BioLink, to display the same information that AmiGO has on their gene product pages. We already seemed to be trying to do something similar (see the equivalent [production page example](https://monarchinitiative.org/gene/HGNC:10848#functions)); however, it looks like in the beta site we removed critical information from the results table. This seems to be some of the cause for the confusion. 
  - @cmungall - it would be very useful finding the time to have a chat about this.
  - @deepakunni3, would you mind please having a look at redoing this call for what we are displaying in these pages? 
  - @kshefchek, @kltm ... please check whether I made any mistakes in this logic. Thanks in advance.

To all of you reading this comment: we don't have much information on the history behind the decisions that led Monarch to display the tables that we currently see in the 'function' facet of the 'gene' pages. This is an attempt to clean up the tables we have (which are confusing and contain unnecessarily repetitive rows).

**Comment by deepakunni3** [comment]
Thanks @monicacecilia and @kltm for that discussion.

I do recall that the association table was simplified in the new Monarch UI such that the same view could be used to represent all types of associations. Of course, this is a limitation since a 'once size fits all' doesn't work as we see here where a simplified table is not sufficient to show all the necessary information tied to an association.

We might have to have type specific pages like Gene.vue, Variant.vue, Function.vue, etc.
Would defer to @kshefchek @kltm and @iimpulse on the right approach.

Regarding my action item: 
> would you mind please having a look at redoing this call for what we are displaying in these pages?

@kltm Lets discuss what are the fields that are currently being dropped by BioLink API. I can add these to the query and the translation done by Ontobio and make sure they are in the response.

**Comment by kltm** [comment]
@deepakunni3 Sounds good. Let's touch bases tomorrow?

**Comment by deepakunni3** [comment]
Sure!

**Comment by monicacecilia** [comment]
Aaaaaaaaaand? @kltm @deepakunni3 - What happened? What's next? The suspense is killing me.... :bowtie:

**Comment by monicacecilia** [comment]
😭

**Comment by monicacecilia** [comment]
Monarch Leads discussed this ticket and agreed that: 
- Updating the page to include more information is not a blocker to release of monarch-ui v1.0. 
- [ ] For v1.0, the 'relation' column on the 'function' tab should be moved to the left, so that the user can read 'relation' --> ' function' --> 'support.' @iimpulse

**Comment by monicacecilia** [comment]
We no longer display this information.
