### ISSUE TITLE
Differentiate text mined disease to phenotype associations

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-ui#20]
see https://github.com/monarch-initiative/monarch-app/issues/1631

**Comment by kshefchek** [comment]
This is a data bug rather than ui, I've added it to the ticket here: https://github.com/monarch-initiative/hpo-annotation-data/issues/167

However, we should notify users that this a text mined associations and we have lower confidence in comparison to the manually curated disease to phenotype associations.

**Comment by kshefchek** [comment]
This is currently not possible in the production db, and text mined associations have been removed in our db moving foward, proposing we close
