### ISSUE TITLE
too many results in search

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-ui#213]
for example, EHLERS-DANLOS SYNDROME, KYPHOSCOLIOTIC TYPE, 1 has 91491 matches
<img width="1440" alt="screen shot 2018-01-24 at 2 14 29 am" src="https://user-images.githubusercontent.com/796636/35309370-705e82d6-00ac-11e8-8c5a-0ab8bf19bf30.png">

**Comment by kshefchek** [comment]
Transferring to the new app as this was never addressed.

@pnrobinson recently discovered another case when querying a HGVS variant label,
https://beta.monarchinitiative.org/search/NM_144997.5(FLCN):c.1429C%3ET%20(p.Arg477Ter)

Setting debugQuery=true, I can the tokenizer is being aggressive with the punctuation in the hgvs format, the tokens queried are:
1. nm
2. 144997.5
3. flcn
4. 1429c
5. t
6. c
7. nm_144997.5(flcn):c.1429c>t
8. nm_144997.5(flcn):c.1429c>t (p.arg477ter))

Which results in many false positives (from a domain perspective).  Some quick ideas

1. Quote all input strings, effectively overriding the tokenizer (could result in a drop in true positives)
2. Test out another tokenizer, eg classic tokenizer instead of standard
3. Use the solr relevancy score and adjust at the UI level, as @kltm suggested above https://github.com/monarch-initiative/monarch-ui/issues/213#issuecomment-361387739

**Comment by pnrobinson** [comment]
@kshefchek @mellybelly I wonder if we can have one search for the initial autocomplete, but once the user presses go, we switch strategies and show only exact or very near matches?

**Comment by kshefchek** [comment]
The keyword tokenizer is the closest we have to an exact match, https://lucene.apache.org/solr/guide/6_6/tokenizers.html#Tokenizers-KeywordTokenizer.  This is one of three we are matching on (standard/classic tokenizer, edge ngram, keyword).  We could go this route but we may lose valid hits, keeping in mind our test cases outlined in https://github.com/monarch-initiative/monarch-app/issues/1383

I tested out the classic tokenizer but this did not help much with the HGVS label, 297106 down to 248200 matches, the only difference is instead of the two tokens
"1429c" and "c", we get "1429c.c", which doesn't help much

**Comment by kshefchek** [comment]
fixed with https://github.com/monarch-initiative/monarch-ui/pull/214
