### ISSUE TITLE
Update table for human transgenes

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#245]
The table displaying results for human transgenes in mouse, fish, fly, etc. has to be updated. 
- Should we have a different category?
- Variant categories with all human variants? 
- Details about human transgenes that includes model information?

**Comment by kshefchek** [comment]
perhaps easier is when we're on a gene page, don't show variants for any different species.  If desired we could have a transgenes tab, but I'm not certain this is useful data for our users, perhaps someone sciency could weigh in @dosumis @monicacecilia @mellybelly

**Comment by pnrobinson** [comment]
There are various kinds of transgenes, and I am not sure that having a fixed page called transgene would be that correct. Transgenes can have WT or mutant sequences for instance, and they can have different kinds of promoters and I believe may sometimes be used in different contexts than "standard" knockouts. I wonder though if this should be a topic for a subsequent release, because it is pretty difficult. Maybe for now we should show them in a separate table or otherwise mark them?

**Comment by pnrobinson** [comment]
@kshefchek It would also be useful to know more about what is happening now. Where do Transgenes typically show up?

**Comment by kshefchek** [comment]
Transgenic variants and genotypes show up on gene pages, although phenotypes are not inferred across them.  To view any phenotypes associated with these you would have to navigate to the variant or genotype page, so they are relatively hard to reach without a lot of clicking.

**Comment by kshefchek** [comment]
For now I've removed transgenic variant to gene associations at the index level by remove 'sequence derives from', easy to bring back if desired.

**Comment by monicacecilia** [comment]
Dear @kshefchek, 
Can we close? 
Else, could we please document what specifically is left ToDo on this ticket?
Thank you! :bowtie:

**Comment by kshefchek** [comment]
fixed with https://github.com/monarch-initiative/monarch-cypher-queries/commit/568f44f63fb2ca1009944c9b6cb3160e77563613
