### ISSUE TITLE
Add additional information/links to current anatomy pages

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/monarch-ui#281]
Currently these pages (https://beta.monarchinitiative.org/anatomy/FBbt:00110671) look quite empty; It would be super cool if we could:

- include xrefs (i.e. linkouts) by default
- include human readable definitions (IAO property)

**Comment by monicacecilia** [comment]
Dear @iimpulse & @kshefchek, could we please bring this also up to our radar and discuss feasibility and timeline? 
Thanks! surpriiiise. 🎉

**Comment by kshefchek** [comment]
@matentzn in order to display definitions we'll need them in our database, same with xrefs. This should come from the monarch merged ontology.  For association data we'll need this in dipper->scigraph->solr->biolink pipeline (or some portion).

https://scigraph-data-dev.monarchinitiative.org/scigraph/graph/FBbt:00110671

Compare to

https://scigraph-data-dev.monarchinitiative.org/scigraph/graph/MONDO:0007947

If it's already in the ontology this would point to an issue upstream in the ontology->scigraph step.

**Comment by monicacecilia** [comment]
@kshefchek - I like your style for closing tickets. 🤠 
Thanks! :bowtie:
