### ISSUE TITLE
Autocomplete ranking in phenotype profile search seems to be off.

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-ui#336]
site search autocomplete ranking makes sense | phenotype autocomplete profile helper does not
--|--
<img width="402" alt="Screen Shot 2020-05-25 at 4 13 30 PM" src="https://user-images.githubusercontent.com/3658863/82847384-b3ffd580-9ea2-11ea-9705-1b6be3269d8d.png">|<img width="614" alt="Screen Shot 2020-05-25 at 4 12 19 PM" src="https://user-images.githubusercontent.com/3658863/82847417-dd206600-9ea2-11ea-8f2c-3a2614135749.png">

**Comment by kshefchek** [comment]
because I can recreate it in chrome and not in firefox, pretty certain it's the application of javascript sort - https://github.com/monarch-initiative/monarch-ui/blob/81acc8e/src/components/MonarchAutocomplete.vue#L296

We should remove and always let the API handle sorting, and I think this code is vestigial anyway
