### ISSUE TITLE
Fix G2D associations, show relationship type prominently

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-ui#39]
Similar to #20 but different

https://alpha.monarchinitiative.org/disease/MONDO:0007947#gene

We don't want this

See email thread re Marfan for context

High priority

**Comment by monicacecilia** [comment]
Correct, it needs to be fixed in alpha. 

It is now fixed in production (see https://monarchinitiative.org/disease/MONDO:0007947#genes - thanks @kshefchek!!) but it has not yet been propagated to alpha. To do that, we need to first add [this filter (#1637)](https://github.com/monarch-initiative/monarch-app/pull/1637) in biolink/ontobio. 

I'll finish the issue in BioLink and link to this one.

**Comment by cmungall** [comment]
I'm going to split this into two separate tickets
