### ISSUE TITLE
Eutils parsing bug on publication pages

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#407]
When debugging why we're not getting reciprocal associations on literature pages I ran into a type error here:

TypeError: v.map is not a function:
https://github.com/monarch-initiative/monarch-ui/blob/92510dd/src/views/Node.vue#L696

There may have been some changes to the xml schema over on eutils so we're getting a string back instead of a list.

**Comment by monicacecilia** [comment]
@jen-martin 👀

**Comment by vincerubinetti** [comment]
Can someone give me more details about this issue? As someone who has looked at the code and app quite a lot but is still new to it, I'm not even 100% sure what page this bug is referring to. Best I can tell, `"reciprocal associations on literature pages"` refers to this page?

![image](https://user-images.githubusercontent.com/8326331/125131535-ebded200-e0d0-11eb-825c-be13b011ab5d.png)

And then clicking on one of the pubmed ids? I believe I'm seeing the described error here: https://monarchinitiative.org/publication/PMID:15287423

I can make the error go away easily, but I assume something is missing because of the error. Is there an example of a pubmed document that is still being processed correctly, ie what it should look like?

Also I encountered this when poking around. Seems like it's a related bug:

![image](https://user-images.githubusercontent.com/8326331/125131384-b76b1600-e0d0-11eb-8e00-339fbd4484f6.png)

**Comment by mellybelly** [comment]
@kshefchek can you take a look pls, thanks

**Comment by kshefchek** [comment]
reciprocal links meaning - if theres a PMID:xyz on the neonatal Marfan syndrome page we would expect to see neonatal Marfan syndrome on the PMID:xyz page (under the disease tab).  I can poke around and see if any of these literature pages are still working.

instead of fixing we may opt to just overhaul these all together given the recent tickets?
