### ISSUE TITLE
Enrich publication representation

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-ui#420]
On the publications tab of each node page

- ~Add First Author last name, Title (First x words ok), Journal (abbreviations OK), Year~ #438 
- Add to the publications node page a hyperlinked list of mentioned diseases, phenotypes, etc. However, these should not be in a table as they might be construed as biological data instead of just context.

**Comment by pnrobinson** [comment]
Sorry @jmcmurry I did not see this until I posted my issues, which partially overlap.

In general I would love to see less use of tabs and to put more information on one page.

**Comment by vincerubinetti** [comment]
@kshefchek or anyone, is there rate limiting on the Entrez API.

I was trying to use the existing `getPublication` function in `src/api/Entrez.js` to get the details for each publication, but I'm getting CORS errors after the first request. If I space out the requests by ~500ms, they don't throw any errors. Any idea why this would be happening?

It looks like the NCBI endpoints we're querying have the option to accept a list of pubmed ids instead of just one, so I'm currently trying to rewrite `getPublication` so that it can accept an array of ids as well.

**Comment by kshefchek** [comment]
they rate limit 3 requests/second without an api key, so sending a batch all at once is the way to go

**Comment by vincerubinetti** [comment]
The first bullet point of this issue is addressed by #438 

As for the second bullet point, how can we implement this. Is this list of mentions something that is already populated in the data somewhere? Can any of the biolink services provide this information somehow?

**Comment by kshefchek** [comment]
for mentions, I think the closest we have is the data that is shown in each table on the publications page, but we should limit these to direct=true since there are also some inferences included otherwise with varying accuracy.

**Comment by vincerubinetti** [comment]
Are you referring to this table:

![image](https://user-images.githubusercontent.com/8326331/127707527-3f43ef3e-dba5-44ff-be0e-b409ad9e9a54.png)

If I have the terminology right, this is not the publication page, but the publication card on a non-publication node page. Also what do you mean by `direct=true`. Is that referring to when `relation` is `source`?

The only mention of `direct` I see in the code is related to phenotypes.

If this is indeed the table you're talking about, then it sounds like Julie's second bullet point is already implemented, it's just that she wants it to not be in tabular format because it could be construed as having biological meaning (perhaps this is also what you meant by "otherwise with varying accuracy")?

I need more clarity here. There's not enough verbosity in this issue for me (as a non-biologist who hasn't been here for the development lifetime of this app) to actually act on and resolve.

**Comment by kshefchek** [comment]
we probably need @jmcmurry to confirm, but I think the second bullet point is for pages like these: https://monarchinitiative.org/publication/PMID:25614286, instead of tabs with tables with a few rows each, listing the ids in those tables on the overview card.  direct=true refers to the biolink calls that happen to generate the tables on the publication page.  It might be easier to ignore that for now and just figure out exactly what this should look like.

**Comment by jmcmurry** [comment]
Was hoping for something more like this. Remove "neighbors" if possible as this isn't relevant for pubs. Hide the left panels as this is more data-ey. We just want to show (and hyperlink) the recognized entities.

![image](https://user-images.githubusercontent.com/3658863/127716127-90184eb2-c032-463c-aef0-f6fa6db23e83.png)

**Comment by vincerubinetti** [comment]
Bullet point 1 is closed by #438.

Since bullet point 2 is larger in scope, I'll do that in a separate pr.

**Comment by monicacecilia** [comment]
First half was solved, second half will be addressed at https://github.com/monarch-initiative/monarch-app/issues/757 
Closing this ticket.
