### ISSUE TITLE
website issue?

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/monarch-ui#440]
## Describe the problem

Is there a website issue? 
https://monarchinitiative.org/disease/MONDO:0030866
data isn't loading only "page frame"

**Comment by kshefchek** [comment]
@vincerubinetti is this something you could investigate?

**Comment by vincerubinetti** [comment]
Looks like the root cause is this query not returning anything and the UI not handling the exception:

https://api.monarchinitiative.org/api/graph/edges/from/MONDO:0030866?relationship_type=equivalentClass&relationship_type=subClassOf&relationship_type=BFO%3A0000050

Not sure how critical the info returned from this query is. I can handle the exception but it might just look like a blank page even so.

Will look into it.

**Comment by kshefchek** [comment]
if this query 404s it means the ID is not in our graph, @ValWood I suspect you manually generated this url or was it linked from another page or website?  We should have a generic message for cases like this

**Comment by ValWood** [comment]
Oh I see that I was searching for an ID that is in the ontology, but not yet in the database.
How frequently do you update the database? this feels like it was added a while ago?

**Comment by ValWood** [comment]
https://github.com/monarch-initiative/mondo/issues/3410
but the ticket where this was fixed  was back in April?
https://github.com/monarch-initiative/mondo/issues/3009
