### ISSUE TITLE
Remove genome feature viewer

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#447]
According to @cmungall the AWS instance supporting this widget is being sunset.  It sounds like the decision is to remove this widget, and perhaps eventually link out to other resources that provide genome browsing.

An example of this widget can be found here - https://monarchinitiative.org/gene/HGNC:10848

![image](https://user-images.githubusercontent.com/1467299/129382563-8573d943-8439-4b80-a140-47838ecc69a9.png)

cc @monicacecilia

**Comment by monicacecilia** [comment]
Yes, exactly Kent. 
There are many other places where people can review these details. We could provide links to genome locations in the resources’ browsers (where appropriate, if they provide them).
Also, looking forward, it would be best to have variants and annotations rather than this type of gene representation.

**Comment by monicacecilia** [comment]
:bowtie:
