### ISSUE TITLE
Add header to definitions and descriptions

### ISSUE THREAD

**Issue by hannahbronstein97** [monarch-initiative/monarch-ui#52]
https://monarchinitiative.org/disease/MONDO:0001476
I am student working with @nicolevasilevsky, she is showing me around the monarch website and I noticed the definitions were not clear. A clear descriptive heading for the definition section would be a great addition.

**Comment by monicacecilia** [comment]
I agree that this would be a good addition, so that instead of this: 
<img width="375" alt="Screen Shot 2019-04-17 at 8 43 52 PM" src="https://user-images.githubusercontent.com/1714621/56316196-99144b00-6151-11e9-9361-f66dae80ddc3.png">

the user sees this, in the case of a disease's definition: 
<img width="375" alt="Screen Shot 2019-04-17 at 8 43 35 PM" src="https://user-images.githubusercontent.com/1714621/56316233-af220b80-6151-11e9-8777-3abfcd54af60.png">

or this, in the case of a gene's description: 
<img width="375" alt="Screen Shot 2019-04-17 at 8 50 39 PM" src="https://user-images.githubusercontent.com/1714621/56316593-923a0800-6152-11e9-8e22-3e59c6ba7456.png">

**Comment by mellybelly** [comment]
+1
