### ISSUE TITLE
Using a gene of interest to generate likely phenotypes

### ISSUE THREAD

**Issue by dnahotline** [monarch-initiative/monarch-ui#70]
This is more of a dumb novice question. I wanted to find out about the phenotype associated with defects in TRIP12. I expect to find phenotypes related to NDD in animals that lack TRIP12, or wtTRIP12 analysis to learn things about TRIP12. Not sure Monarch has this information. As a user, this would be a useful feature.

**Comment by monicacecilia** [comment]
Dear @dnahotline 
To help us better understand your question, could you please explain more about:
- the page where you started
- the term you were trying to use (as an example)
- where you tried to enter it
- what happened when you did

**Comment by dnahotline** [comment]
Here is a screenshot. The text for what I did, and what I was after, was listed previously (above).
<img width="1062" alt="Screenshot 2019-05-13 16 30 02" src="https://user-images.githubusercontent.com/23179382/57660650-63218580-759c-11e9-90ee-e23a9d69c5c9.png">

**Comment by dnahotline** [comment]
the page where you started: https://beta.monarchinitiative.org/analyze/phenotypes
the term you were trying to use (as an example): TRIP12
where you tried to enter it: only place a gene can be entered is the second box
what happened when you did: a list of TRIP12 orthologs was generated. When I follow one of the links it just gives me a link to NCBI. The links in the side panel do not seem to lead anywhere, eg, "overview" and "facets" and "neighbors"--see screenshot.
<img width="892" alt="Screenshot 2019-05-13 16 41 03" src="https://user-images.githubusercontent.com/23179382/57661034-01fab180-759e-11e9-80a1-f229bfa657cc.png">

**Comment by monicacecilia** [comment]
The behaviour has been updated so that: 
- when entering a term (e.g., TRIP12) in the 'Genes' box, and hitting the 'return' button (without clicking on one of the suggested terms from autocomplete), the user is redirected to the table of results from the 'Search' box (see screenshot).

![Screen Shot 2019-07-02 at 1 42 49 PM](https://user-images.githubusercontent.com/1714621/60545248-7bc23800-9ccf-11e9-867e-fa7875ee448c.png)


- It is also possible to use a gene of interest to generate a list of phenotypes, per species. For example, from the list of species in the left column (see image above), the user can choose a species of interest, and once the reduced list is generated, clicking on the gene entry for that species will provide all available information about the gene, as shown here: 

![Screen Shot 2019-07-02 at 2 09 29 PM](https://user-images.githubusercontent.com/1714621/60546875-212adb00-9cd3-11e9-8246-1ceb8ffe2692.png)

- From the column on the left, choosing the tab that lists 'Phenotypes' will display a table of results with all phenotypes associated with this gene, as shown here: 

![Screen Shot 2019-07-02 at 1 52 40 PM](https://user-images.githubusercontent.com/1714621/60546960-5afbe180-9cd3-11e9-9235-d4a5b891693d.png)


--

- if the user chooses (clicks on) one of the options listed from autocomplete, the options to use the tool by building a profile of phenotypes and a list genes from different species to compare across will appear, and the 'Run Similarity Analysis' button will also be available. The results will be displayed at the bottom of the page (see screenshot). 

![Screen Shot 2019-07-02 at 1 48 09 PM](https://user-images.githubusercontent.com/1714621/60545607-51bd4580-9cd0-11e9-8347-6f6549ae5e90.png)

**Comment by pnrobinson** [comment]
I think @dnahotline question was more sophisticated than this. There have been some studies that used the profile of gene orthologues in different species to try and find new disease genes. If you think that species X has a certain function that humans have then we can conclude that a human gene that has no orthologue in X probably does not implement the function in question. An even more sophisticated analysis would be required to start an analysis like this from phenotypes. The Monarch website does not currently implement this functionality. Personally I think that this kind of analysis will need to be specialized for each question to make any sense and so it is not easy to do this in a website.
@monicacecilia  I think that this issue can be closed or are there pending items?

**Comment by monicacecilia** [comment]
It has been completed.  I was waiting to hear any final deedback from @dnahotline. It has been 2 weeks and I'm closing.
