### ISSUE TITLE
Add "how to cite Monarch" page

### ISSUE THREAD

**Issue by nlharris** [monarch-initiative/monarch-ui#75]
The website could use a page about how to cite the project. It could be added to the About menu and also linked or mentioned on https://monarchinitiative.org/page/links.
Relates to https://github.com/monarch-initiative/monarch-app/issues/1191 (I'm not sure if there's a way to add links to other issues?)

**Comment by monicacecilia** [comment]
Proposed text for 'how to cite Monarch' page: 
-----------

Please acknowledge the use of Monarch with the following paragraph: 
{YOUR resource} uses and displays data and algorithms from the Monarch Initiative. The Monarch Initiative (https://monarchinitiative.org) makes biomedical knowledge exploration more efficient and effective by providing tools for genotype-phenotype analysis, genomic diagnostics, and precision medicine across broad areas of disease. 

To cite the use of Monarch in publications, please use these two references:
Navigating the Phenotype Frontier: The Monarch Initiative. McMurry et al. GENETICS August 1, 2016 vol. 203 no. 4 1491-1495; DOI: 10.1534/genetics.116.188870
The Monarch Initiative: an integrative data and analytic platform connecting phenotypes to genotypes across species. Mungall et al. Nucleic Acids Res. 2017 Jan 4; 45(Database issue): D712–D722. Published online 2016 Nov 29. doi: 10.1093/nar/gkw1128

To cite a specific data page or result in Monarch:
Because most of the association content in Monarch comes from external sources, we kindly ask thatPlease cite the original database records (e.g. http://www.informatics.jax.org/accession/MGI:1915196) or the original publications (e.g. PMID:25605924), as appropriate.

If you wish to link from your site to a specific data page from the Monarch Initiative website, or link to algorithmic results as presented in Monarch, please do so using our permalinks (a.k.a. "HTTP URI"). The permalink for each data page starts with the Monarch URL https://monarchinitiative.org/ followed by the entity's prefixed accession (e.g. OMIM:154700); in this example, the permalink would be https://monarchinitiative.org/OMIM:154700. 

For example, the suggested citation for this record from OMIM at Monarch Initiative would be as follows:  
Prefixed Identifier: OMIM:154700	
http URI/permalink: https://monarchinitiative.org/OMIM:154700	
Suggested citation: Monarch Consortium. Accessed 2016-09-22. Marfan Syndrome. https://monarchinitiative.org/OMIM:154700

The complete set of transformed data for a given source database can be found at http://data.monarchinitiative.org/ttl/

Please note that the data in Monarch is constantly expanding and improving. The data is versioned with each database release, and archived database releases are available upon request. The evolution of individual records in Monarch is not currently tracked. More documentation about our identifiers can be found in GitHub, at https://github.com/monarch-initiative/dipper/blob/master/README.md#identifiers

**Comment by monicacecilia** [comment]
p.s: This information came from older documents I found on the `Monarch project docs` directory in the shared Google Drive. Please feel free to edit as you see fit.
