### ISSUE TITLE
Provenance of pathway annotations are not very clear

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-ui#97]
E.g. http://beta.monarchinitiative.org/phenotype/HP:0003474#pathway

![image](https://user-images.githubusercontent.com/50745/59243355-65d7c080-8bc4-11e9-960f-91edd4f2f391.png)

I don't think there is any one single source here. This is a join between reactome pathway gene -> disease -> phenotype in monarch-solr-queries?

Not sure why Coriell comes into the picture at all?

I suggest as a first pass having an info box for each tab, e.g. "monarch phenotype pathway associations are derived from combining phenotype to gene info with info from Reactome about which gene is involved with each pathway". Ideally this would be more data/metadata driven

**Comment by pnrobinson** [comment]
There seems to be a larger bug on this page. I was looking at pathways related to impaired proprioception. There are two things that appear wrong to me

  1.  “Pathways” are often apparently literature assertions about pathways, e.g., the number 1 hit here – shouldn’t we be restricting ourselves to Reactome or GO terms here?
  2.  This is related to “Gait ataxia” on the webpage, but it is unclear what relation this has to “Impaired proprioception”
Also, in general, it seems that we are associating 378 pathways to one relatively specific HPO term (impaired proprioception). While biology is complicated, it probably (!) is not that complicated, and so the process by which we are associating pathways and phenotypes might be too general? In any case, it would be good for the user to get some more information about why we think these pathways are associated to these phenotypes. I realize there is no one correct answer, but I would suggest we consider being stricter about how we related pathways to phenotypes – I am not sure what researchers would do with information like this – it would be a lifetime of experiments to investigate the pathophysiology of impaired proprioception. Maybe we can introduce some sort of scoring mechanism so that the hits are ranked?
-Peter


Impaired proprioception
Abnormality of proprioception
 720  pathway associations.
Pathway
Relation
Phenotype
Support
MECP2 regulates transcription of genes involved in GABA signaling<http://beta.monarchinitiative.org/pathway/REACT:R-HSA-9022927>
Unknown<http://purl.obolibrary.org/obo/RO_Unknown>
Gait ataxia<http://beta.monarchinitiative.org/phenotype/HP:0002066>

**Comment by monicacecilia** [comment]
- Suggestion to relabel this as 'Potential Pathway Implications' instead of current 'pathway associations.'
- Given Chris' and Peter's comments, is it appropriate to even have this information? Do we want to keep it?

**Comment by pnrobinson** [comment]
@cmungall We need more feedback to be able to implement anything here. This seems to me to be primarily a modeling/backend issue (see my comments about the 'errors' above). I am going to mark this as blocked by API. If you think I am wrong then we need to discuss how to implement this, as I do not think we can do anything sensible with the current API.

**Comment by monicacecilia** [comment]
Suggestion to hide pathway pages for now.
We should stop indexing it for now, until we figure out what it is that we are querying and how we plan to use the results. 
Punting to v1.1 for now.

**Comment by kshefchek** [comment]
fixed with https://github.com/monarch-initiative/monarch-ui/pull/224
